import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import type McpPlugin from '../main';
import type { McpLogger } from '../logging';
import { registerGetActiveFile } from './get-active-file';
import { registerReadNote } from './read-note';
import { registerAppendDailyNote } from './append-daily-note';
import { registerListFolder } from './list-folder';
import { registerListAllTags } from './list-all-tags';
import { registerSearchNotes } from './search-notes';
import { registerDescribeVault } from './describe-vault';
import { registerCreateNote } from './create-note';
import { registerEditNote } from './edit-note';
import { registerDeleteNote } from './delete-note';
import { registerGetNoteMetadata } from './get-note-metadata';
import { registerListRecentNotes } from './list-recent-notes';
import { registerSearchContent } from './search-content';
import { registerListSessions } from './list-sessions';
import { registerGetBacklinks } from './get-backlinks';
import { registerAppendNote } from './append-note';
import { registerCreateFolder } from './create-folder';
import { registerRenameNote } from './rename-note';
import { registerPatchNote } from './patch-note';
import { registerReadAttachment } from './read-attachment';
import { registerAddAttachment } from './add-attachment';

export function registerTools(mcp: McpServer, plugin: McpPlugin, logger: McpLogger): void {
    const tracker = plugin.statsTracker;
    registerGetActiveFile(mcp, plugin, tracker, logger);
    registerReadNote(mcp, plugin, tracker, logger);
    registerAppendDailyNote(mcp, plugin, tracker, logger);
    registerListFolder(mcp, plugin, tracker, logger);
    registerListAllTags(mcp, plugin, tracker, logger);
    registerSearchNotes(mcp, plugin, tracker, logger);
    registerDescribeVault(mcp, plugin, tracker, logger);
    registerCreateNote(mcp, plugin, tracker, logger);
    registerEditNote(mcp, plugin, tracker, logger);
    registerDeleteNote(mcp, plugin, tracker, logger);
    registerGetNoteMetadata(mcp, plugin, tracker, logger);
    registerListRecentNotes(mcp, plugin, tracker, logger);
    registerSearchContent(mcp, plugin, tracker, logger);
    registerListSessions(mcp, plugin, tracker, logger);
    registerGetBacklinks(mcp, plugin, tracker, logger);
    registerAppendNote(mcp, plugin, tracker, logger);
    registerCreateFolder(mcp, plugin, tracker, logger);
    registerRenameNote(mcp, plugin, tracker, logger);
    registerPatchNote(mcp, plugin, tracker, logger);
    registerReadAttachment(mcp, plugin, tracker, logger);
    registerAddAttachment(mcp, plugin, tracker, logger);
}
